---
title: "Introduction"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
<font size = 4>
Diabetes is a chronic disease whose prevalence has increased rapidly in the past few decades. According to the report from WHO, in 2014, the prevalence of diabetes among adult population had risen from 4.7% to 8.5%  comparing to that in 1980 (WHO, 2016). It is projected as the seventh leading cause of mortality in 2030 (Mathers & Loncar, 2006).  

In the U.S., the data of 2015 shows that 7.2% of the population are diagnosed with Diabetes(CDC, 2017). In 2013, it ranked as the seventh leading cause of death in the nation (CDC). Previous studies identified obesity as the main risk factor of type 2 diabetes (which account for 95% cases of diabetes in the U.S.)(Smyth & Heron, 2006). Meanwhile,  consumption of artificial sweetened beverage(Koning et al, 2011) and  prenatal exposure to famine under certain circumstances(Lumey, Khalangot & Vaiserman, 2015) are both related to the increased prevalence of type 2 diabetes. The report from CDC also demonstrates that there are certain association between socioeconomic status and the prevalence(CDC, 2017). 

Inspiring by these findings which are all somehow related to food environment, we set the goal to explore the association between prevalence of diabetes in United States and food related factors, including median household income, participation proportion of National School Lunch Program (NSLP)/School Breakfast Program (SBP), average number of supermarket and grocery stores/1,000 residents, fast-food restaurants availability, etc. The research focuses on population scale where we explore the relationship between stately diabetes rate and multiple factors of the state. 
</font>