---
title: "Diabetes VS food environment Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
```

```{r}
library(tidyverse)
library(janitor)
library(ggridges)
library(ggthemes)
library(stringr)
library(dplyr)
library(forcats)

library(plotly)
```

```{r}
health = 
  readxl::read_xls('../data/food_enviroment_atlas.xls', sheet = 'HEALTH') %>%
  clean_names() %>%
  select(1:7)

medhincome_08 = readxl::read_xls("../data/mhi_08.xls", range = "A13:B63",col_names = c("state","medhhinc08")) %>%
  clean_names() %>%
  mutate(state = state.abb[match(state,state.name)])
medhincome_08$state[17] = "DC"

medhincome_13 = readxl::read_xls("../data/mhi_13.xls", range = "A11:B61",col_names = c("state","medhhinc13")) %>%
  clean_names() %>%
  mutate(state = state.abb[match(state,state.name)])
medhincome_13$state[8] = "DC"

medhincome = merge(medhincome_08, medhincome_13,by=c("state"))

diabetes = health %>%
  select(state, county, pct_diabetes_adults08, pct_diabetes_adults13) %>%
  gather(key = year, value = pct_diabetes_adults, pct_diabetes_adults08:pct_diabetes_adults13)%>%
  separate(year, into = c("remove", "year"), sep = -3) %>%
  select(-remove)

obese = health %>%
  select(state, county, pct_obese_adults08, pct_obese_adults13)%>%
  gather(key = year, value = pct_obese_adults, pct_obese_adults08:pct_obese_adults13)%>%
  separate(year, into = c("remove", "year"), sep = -3) %>%
  select(-remove)

health_status = merge(diabetes, obese, by=c("state","county", "year"))

```


Column {data-width=450}
-----------------------------------------------------------------------

### Scatter plot of the association between adult obesity rate and diabetes rate (at county level)
```{r}
f <- list(
  family = "Courier New, monospace",
  size = 18,
  color = "#7f7f7f"
)
x <- list(
  title = "Obesity Rate",
  titlefont = f
)
y <- list(
  title = "Diabetes Rate",
  titlefont = f
)

health_status %>%
  filter(year == "13") %>%
  mutate(text_label = str_c("State: ", state, '\nCounty: ', county)) %>% 
  plot_ly(x = ~pct_obese_adults, y = ~pct_diabetes_adults, type = "scatter", mode = "markers",
          alpha = 0.8, 
          color = ~state,
          text = ~text_label) %>%
  layout(xaxis = x, yaxis = y) 

```


Column {data-width=400}
-----------------------------------------------------------------------

### Boxplot of Diabetes rate for each state in 2013 (more variation can be found at county level)

```{r}
x <- list(
  title = " ",
  titlefont = f
)
y <- list(
  title = "Diabetes Rate",
  titlefont = f
)
health_status %>%
  filter(year == "13") %>%
  group_by(state) %>%
  plot_ly(color = ~state, y = ~pct_diabetes_adults, type = "box", colors = "Set2")  %>%
  layout(xaxis = x, yaxis = y)
```


### Boxplot of Obesity rate for each state in 2013 (more variation can be found at county level)

```{r}
x <- list(
  title = " ",
  titlefont = f
)
y <- list(
  title = "Obesity Rate",
  titlefont = f
)
health_status %>%
  filter(year == "13") %>%
  group_by(state) %>%
  plot_ly(color = ~state, y = ~pct_obese_adults, type = "box", colors = "Set2")  %>%
  layout(xaxis = x, yaxis = y)
```
